### PR TITLE
Cicd cleanup

### PR DESCRIPTION
**Pull request by meytalmesh**

### CODE REVIEW

**Comment by meytalmesh** [comment]
CICD updates and clean up

**Comment by meytalmesh** [comment]
added GH, azure, Jenkins templates in java, nodeJS, dotNet

**Comment by meytalmesh** [comment]
@meytalmesh
CICD new tamplates in Azure, BitBucket and GH Actions
added some comments.

**Comment by jonathan-gruber** [comment]
@maxjeffos any chance you could review and approve this merge please?

**Review by jonathan-gruber — APPROVED** [review]

**Pull request merged**
